from __future__ import annotations

DEFAULT_STORY_TEXTS: dict[str, list[str]] = {
    "morning": [
        "Guten Morgen. Heute darfst du langsam starten.",
        "Guten Morgen. Erst atmen, dann alles andere.",
        "Guten Morgen. Mach dir den Tag nicht schwerer als er ist.",
        "Guten Morgen. Ein ruhiger Kopf ist heute mehr wert als Hektik.",
        "Guten Morgen. Lass dich heute nicht von jedem Gedanken stressen.",
        "Guten Morgen. Du musst heute nicht perfekt sein, nur da.",
        "Guten Morgen. Nimm dir kurz Zeit für dich, bevor der Tag laut wird.",
        "Guten Morgen. Vielleicht wird heute leichter, als du gerade denkst.",
        "Guten Morgen. Kaffee hilft, aber Ruhe hilft manchmal mehr.",
        "Guten Morgen. Heute lieber klar statt schnell.",
        "Guten Morgen. Fang klein an, das reicht oft schon.",
        "Guten Morgen. Ein guter Tag beginnt nicht mit Druck.",
        "Guten Morgen. Schick dir selbst heute ein bisschen Geduld.",
        "Guten Morgen. Lass dir den Tag nicht von Eile stehlen.",
        "Guten Morgen. Ich schick dir Ruhe, Fokus und einen kleinen Gruß.",
        "Guten Morgen. Heute reicht ein klarer erster Schritt.",
        "Guten Morgen. Fang mit Ruhe an, nicht mit Hast.",
        "Guten Morgen. Du musst nicht sofort alles im Griff haben.",
        "Guten Morgen. Vielleicht wird dieser Tag still gut.",
        "Guten Morgen. Ein sanfter Start ist auch ein guter Start.",
        "Guten Morgen. Nimm dir einen Moment, bevor du alles gibst.",
        "Guten Morgen. Lass den Tag dich finden, nicht hetzen.",
        "Guten Morgen. Heute lieber bewusst als überladen.",
        "Guten Morgen. Dein Tempo darf heute freundlich sein.",
        "Guten Morgen. Starte mit einem ruhigen Gedanken in den Tag.",
        "Guten Morgen. Was heute zählt, darf auch klein beginnen.",
        "Guten Morgen. Sei heute sanft zu dir, bevor die Welt laut wird.",
        "Guten Morgen. Vielleicht brauchst du heute weniger Müssen und mehr Sein.",
        "Guten Morgen. Die ersten Minuten gehören heute dir.",
        "Guten Morgen. Es ist okay, wenn der Tag erst langsam Farbe bekommt.",
        "Guten Morgen. Heute musst du nicht beeindrucken, nur anfangen.",
        "Guten Morgen. Sammel dich erst, dann starte los.",
        "Guten Morgen. Ein bisschen Frieden im Kopf ist heute schon viel.",
        "Guten Morgen. Du darfst heute mit Ruhe statt mit Druck beginnen.",
        "Guten Morgen. Lass den Morgen freundlich mit dir umgehen.",
        "Guten Morgen. Heute lieber echt als perfekt.",
        "Guten Morgen. Gib dem Tag eine Chance, ohne ihn sofort zu überladen.",
        "Guten Morgen. Vielleicht wird aus wenig Druck ein guter Tag.",
        "Guten Morgen. Nimm nur mit, was du heute wirklich brauchst.",
        "Guten Morgen. Auch leise Morgen können stark sein.",
        "Guten Morgen. Fang da an, wo du gerade bist.",
        "Guten Morgen. Dein Tag muss nicht schnell sein, um gut zu werden.",
        "Guten Morgen. Heute erst bei dir ankommen, dann im Alltag.",
        "Guten Morgen. Ein klarer Kopf ist heute dein schönstes Extra.",
        "Guten Morgen. Du darfst die ersten Minuten langsam behalten.",
        "Guten Morgen. Lass den Tag heute nicht gegen dich anlaufen.",
        "Guten Morgen. Weniger Druck macht oft mehr möglich.",
        "Guten Morgen. Vielleicht ist heute genau richtig für einen ruhigen Anfang.",
        "Guten Morgen. Trage heute nicht schon morgens den ganzen Tag auf den Schultern.",
        "Guten Morgen. Ein freundlicher Gedanke reicht oft für den ersten Schritt.",
    ],
    "day": [
        "Ein kleiner Gruß für zwischendurch. Trink was und atme einmal tief durch.",
        "Nur kurz hallo. Du musst nicht alles heute sofort schaffen.",
        "Ein kurzer Gruß am Mittag. Weniger Druck sieht dir besser aus.",
        "Kleiner Reminder für heute. Nicht jede Nachricht ist ein Notfall.",
        "Liebe Grüße zwischendurch. Mach langsam, wenn dein Kopf laut wird.",
        "Ein kurzer Halt mitten im Tag. Du darfst kurz raus aus dem Tempo.",
        "Nur ein kleiner Gruß. Vielleicht brauchst du gerade genau diesen Moment.",
        "Zwischendurch mal kurz: Du machst das besser, als du denkst.",
        "Ein Gruß für deinen Feed. Heute lieber bei dir bleiben als überall zugleich.",
        "Kurze Pause in Story-Form. Schultern runter, Blick nach vorn.",
        "Nur kurz da gelassen: Hab einen sanften Tag mit wenig Drama.",
        "Ich schick dir einen kleinen Gruß. Und ein bisschen weniger inneren Lärm.",
        "Für zwischendurch: Nicht jeder Tag muss glänzen, um gut zu sein.",
        "Ein kleiner Gruß am Tag. Bleib weich, auch wenn alles schnell ist.",
        "Kurz an dich gedacht. Hoffe, dein Tag ist freundlicher als dein Kalender.",
        "Ein kleiner Gruß. Vielleicht brauchst du gerade eher Luft als Leistung.",
        "Kurzer Zwischenstopp. Nicht alles verdient heute deine Energie.",
        "Hallo zwischendurch. Gönn dir einen Moment ohne Tempo.",
        "Ein kleiner Tagesgruß. Mach nicht aus jeder Aufgabe einen Berg.",
        "Kurz reingeschoben in deinen Tag: Du darfst auch mal durchatmen.",
        "Ein stiller Gruß für heute. Weniger Hektik steht dir gut.",
        "Falls du es gerade brauchst: Es ist okay, kurz langsamer zu werden.",
        "Ein kleiner Reminder mitten im Tag. Du bist kein Notfallmodus.",
        "Nur kurz hier. Trink was, lockere die Schultern und mach weiter in deinem Tempo.",
        "Ein Gruß zur Tagesmitte. Lass dich nicht von allem gleichzeitig ziehen.",
        "Kurz gesagt: Nicht alles muss heute auf einmal passieren.",
        "Ein Moment für dich. Auch mitten im Tag darf es leiser sein.",
        "Zwischendurch ein kleiner Gruß. Du musst nicht überall gleichzeitig funktionieren.",
        "Ein kurzer Halt. Vielleicht brauchst du gerade eher Ruhe als Motivation.",
        "Hallo im Vorbeiscrollen. Dein Tag darf einfacher bleiben als dein Kopf es sagt.",
        "Kurzer Gedanke für heute. Weniger inneres Rennen, mehr klarer Blick.",
        "Ein kleiner Gruß aus der Mitte des Tages. Nimm dir kurz den Druck raus.",
        "Zwischendurch mal ehrlich: Du darfst eine Pause brauchen.",
        "Nur kurz da. Dein Tempo muss heute niemandem etwas beweisen.",
        "Ein sanfter Gruß. Vielleicht ist langsam heute die bessere Antwort.",
        "Kleine Story, kleiner Reminder: Du musst nicht alles tragen.",
        "Ein Gruß für deinen Tag. Lass dich nicht von Kleinem aus dem Gleichgewicht holen.",
        "Kurz an dich gedacht. Hoffentlich war heute schon etwas Leichtes dabei.",
        "Ein kleiner Tagesgruß. Bleib bei dir, auch wenn viel um dich herum will.",
        "Zwischendurch ein Satz für dich: Du machst genug.",
        "Nur kurz hallo. Manchmal ist ein stiller Moment produktiver als noch mehr Druck.",
        "Ein kleiner Gruß. Du darfst heute freundlich mit deiner Energie umgehen.",
        "Kurze Pause in deinem Feed. Nicht alles muss jetzt entschieden werden.",
        "Ein Gruß am Tag. Lass heute nicht jede Kleinigkeit so groß werden.",
        "Nur kurz: Es ist okay, wenn du heute nicht dauernd glänzt.",
        "Ein kleiner Gruß zur Mitte des Tages. Bleib weich und klar zugleich.",
        "Zwischendurch für dich: Ein tiefer Atemzug ist nie verschwendet.",
        "Ein kurzer Gruß. Vielleicht brauchst du gerade eher Ruhe als noch ein Ziel.",
        "Nur kurz im Feed gelandet: Du darfst auch ohne Dauerstress vorankommen.",
        "Ein kleiner Tagesgruß. Manchmal reicht es, einfach dran zu bleiben.",
    ],
    "evening": [
        "Schönen Abend. Lass den Rest des Tages heute einfach leiser werden.",
        "Schönen Abend. Nicht alles, was heute offen blieb, muss dich jetzt begleiten.",
        "Schönen Abend. Mach es dir heute ein bisschen leichter.",
        "Schönen Abend. Jetzt darf der Kopf langsam Feierabend haben.",
        "Schönen Abend. Lass heute nicht jeden Gedanken mit auf die Couch.",
        "Schönen Abend. Ein ruhiger Abend ist manchmal alles, was man braucht.",
        "Schönen Abend. Vielleicht brauchst du heute nichts mehr leisten, nur ankommen.",
        "Schönen Abend. Weniger müssen, mehr atmen.",
        "Schönen Abend. Lass dir den Rest des Tages nicht von Kleinigkeiten nehmen.",
        "Schönen Abend. Heute darfst du weicher mit dir sein.",
        "Schönen Abend. Nimm nur das mit in den Abend, was dir gut tut.",
        "Schönen Abend. Ich schick dir ein bisschen Ruhe für später.",
        "Schönen Abend. Was heute schwer war, muss nicht den ganzen Abend bleiben.",
        "Schönen Abend. Vielleicht ist jetzt genau die richtige Zeit, langsamer zu werden.",
        "Schönen Abend. Ein kleiner Gruß und etwas Wärme für deinen Feed.",
        "Schönen Abend. Du darfst jetzt Schritt für Schritt runterfahren.",
        "Schönen Abend. Heute nicht mehr alles mit dir herumtragen.",
        "Schönen Abend. Es reicht, wenn der Tag jetzt leiser endet.",
        "Schönen Abend. Vielleicht braucht dein Kopf heute nur weniger Input.",
        "Schönen Abend. Lass den Druck von heute nicht mit in deine Ruhe.",
        "Schönen Abend. Jetzt darf der Rest langsam unwichtig werden.",
        "Schönen Abend. Mach Raum für einen ruhigen Gedanken.",
        "Schönen Abend. Du musst gerade nichts mehr beweisen.",
        "Schönen Abend. Vielleicht ist Weichwerden heute die beste Idee.",
        "Schönen Abend. Lass die Welt heute ein bisschen draußen.",
        "Schönen Abend. Was heute nicht fertig wurde, darf bis morgen warten.",
        "Schönen Abend. Dein Abend muss nicht produktiv sein, nur gut für dich.",
        "Schönen Abend. Fahr runter, ohne dich dafür zu rechtfertigen.",
        "Schönen Abend. Heute darf weniger genug sein.",
        "Schönen Abend. Lass die Unruhe nicht mit in deine Stille.",
        "Schönen Abend. Es ist Zeit, dem Tag langsam die Lautstärke zu nehmen.",
        "Schönen Abend. Sammel dich wieder ein, Stück für Stück.",
        "Schönen Abend. Heute nicht mehr gegen jeden Gedanken kämpfen.",
        "Schönen Abend. Ruhe ist heute wichtiger als noch ein offener Punkt.",
        "Schönen Abend. Mach dir den Abend nicht enger als nötig.",
        "Schönen Abend. Vielleicht brauchst du gerade nur Wärme und wenig Worte.",
        "Schönen Abend. Lass los, was heute nur noch schwer macht.",
        "Schönen Abend. Der Tag darf jetzt hinter dir bleiben.",
        "Schönen Abend. Ein weicher Abend ist manchmal die halbe Erholung.",
        "Schönen Abend. Nimm heute nicht alles mit in die Nacht.",
        "Schönen Abend. Der Rest darf warten, du nicht.",
        "Schönen Abend. Leg den Tag ein bisschen weiter weg von dir.",
        "Schönen Abend. Jetzt ist ein guter Moment für weniger Denken.",
        "Schönen Abend. Lass heute nicht zu viel in deinem Kopf wohnen.",
        "Schönen Abend. Vielleicht ist genau jetzt Zeit für Stille.",
        "Schönen Abend. Du darfst heute früher weich werden.",
        "Schönen Abend. Ein ruhiger Abend ist auch ein guter Abschluss.",
        "Schönen Abend. Bring nur das mit in den Abend, was freundlich zu dir ist.",
        "Schönen Abend. Weniger To-do, mehr bei dir ankommen.",
        "Schönen Abend. Heute reicht ein bisschen Ruhe schon weit.",
    ],
    "night": [
        "Gute Nacht. Hab schöne Träume und ein ruhiges Herz.",
        "Gute Nacht. Lass den Tag jetzt endlich los.",
        "Gute Nacht. Nicht jeder Gedanke muss mit ins Bett.",
        "Gute Nacht. Morgen darf vieles leichter sein.",
        "Gute Nacht. Schlaf weich und denk heute nicht mehr zu viel.",
        "Gute Nacht. Du musst heute nichts mehr lösen.",
        "Gute Nacht. Lass Ruhe gewinnen, nicht das Gedankenkarussell.",
        "Gute Nacht. Hab schöne Träume und weniger Lärm im Kopf.",
        "Gute Nacht. Der Tag ist vorbei, du darfst jetzt einfach nur müde sein.",
        "Gute Nacht. Heute bitte sanft schlafen und freundlich träumen.",
        "Gute Nacht. Morgen ist da, auch ohne dass du jetzt noch alles sortierst.",
        "Gute Nacht. Schließ den Tag ab, nicht dein Herz.",
        "Gute Nacht. Die schönsten Gedanken dürfen heute bei dir bleiben.",
        "Gute Nacht. Für alles andere ist morgen noch Zeit.",
        "Gute Nacht. Ich schick dir Ruhe, Wärme und schöne Träume.",
        "Gute Nacht. Lass die Anspannung von heute langsam aus dir raus.",
        "Gute Nacht. Heute muss nichts mehr geklärt werden.",
        "Gute Nacht. Schlaf in Frieden mit dem, was heute war.",
        "Gute Nacht. Du darfst jetzt weich werden und still.",
        "Gute Nacht. Der Abend ist vorbei, jetzt zählt nur noch Ruhe.",
        "Gute Nacht. Lass dein Herz heute etwas langsamer schlagen.",
        "Gute Nacht. Nimm bitte nicht jeden Restgedanken mit unter die Decke.",
        "Gute Nacht. Morgen darfst du neu auf die Dinge schauen.",
        "Gute Nacht. Dein Kopf muss heute nicht bis zuletzt wach bleiben.",
        "Gute Nacht. Es ist genug für heute, wirklich.",
        "Gute Nacht. Leg den Tag ab, bevor du die Augen schließt.",
        "Gute Nacht. Schlaf heute mit etwas mehr Frieden als Zweifel.",
        "Gute Nacht. Nicht alles braucht noch eine Antwort vor dem Schlafen.",
        "Gute Nacht. Ruhe darf heute wichtiger sein als Ordnung im Kopf.",
        "Gute Nacht. Lass den Tag still ausklingen und dich sanft werden.",
        "Gute Nacht. Morgen hat Platz für alles, was heute liegen blieb.",
        "Gute Nacht. Schlaf dich zurück in etwas Leichtigkeit.",
        "Gute Nacht. Heute endet der Tag ohne dass du ihn noch retten musst.",
        "Gute Nacht. Gönn dir Stille ohne schlechtes Gewissen.",
        "Gute Nacht. Der schönste Abschluss ist manchmal einfach Ruhe.",
        "Gute Nacht. Lass dein Herz zuerst schlafen, dann den Rest.",
        "Gute Nacht. Alles, was heute laut war, darf jetzt leise werden.",
        "Gute Nacht. Nimm nur Wärme mit in den Schlaf.",
        "Gute Nacht. Du darfst loslassen, auch wenn nicht alles perfekt war.",
        "Gute Nacht. Für schwere Gedanken ist das Kopfkissen nicht zuständig.",
        "Gute Nacht. Heute endet hier, und das reicht.",
        "Gute Nacht. Schlaf sanft und nimm dir den Druck nicht mit.",
        "Gute Nacht. Manchmal ist Ausruhen die beste Antwort.",
        "Gute Nacht. Alles Weitere gehört jetzt nicht mehr in diesen Moment.",
        "Gute Nacht. Lass die Müdigkeit gewinnen und nicht die Grübelei.",
        "Gute Nacht. Schlaf heute ein bisschen leichter als gestern.",
        "Gute Nacht. Dein Morgen braucht kein nächtliches Gedankenchaos.",
        "Gute Nacht. Es darf still werden, auch in dir.",
        "Gute Nacht. Halt heute nicht länger fest, was gehen darf.",
        "Gute Nacht. Ich schick dir einen sanften Schlussstrich für heute.",
    ],
}